### ISSUE TITLE
No weather icons with 2024.8

### ISSUE THREAD

**Issue by Maddin1684** [mlamberts78/weather-chart-card#222]
With Core Update 2024.8 no weather-icons are shown.

**Desktop (please complete the following information):**
 - WEATHER-CHART-CARD VERSION 2.4.7
 - HOME ASSISTANT VERSION AND INSTALLATION TYPE 2024.8
![IMG_0076](https://github.com/user-attachments/assets/2a63aa91-6183-49e9-8729-9d9c98200685)

**Comment by knuckleheadsmiff** [comment]
I’m seeing the same thing on my iPad running the home assistant app.

**Comment by Maddin1684** [comment]
Can confirm, only on iPad companion app. 
iPhone oder safari browser on iPad works fine.

**Comment by knuckleheadsmiff** [comment]
On the iPhone and in the safari browser things look slightly better but the weather icons are still not showing. 

![IMG_4780](https://github.com/user-attachments/assets/38cf4b89-7612-4da3-a5e8-744a2283e4a3)

**Comment by nvdael** [comment]
Same here.
Only iPad companion app, Safari on iPad is broken. 
Android Phone and Windows Desktop both with Edge no problems.
No themes loaded.

**Comment by vlado05** [comment]
Same here.
Fully kiosk browser on NSPanel pro.

**Comment by Kanecaine** [comment]
Having this problem since the update to HA 2024.8 on iPad using the official companion app. On same iPad with Safari everything is ok. I can produce the error already in the card selection:

![IMG_0872](https://github.com/user-attachments/assets/48344308-e0e6-4c20-945d-764f11502c11)

I inspected the rendered HTML and found out that it might has to come from the rendered style-Tag right before the ha-card-tag. The big "25" (same as the "50" in comment #1) comes from the icon-size. When i change the default value in the ui config of the card from "25" to "24" than a big 24 is rendered instead. It gets even more strange when i delete the icon-size in the ui config: in this case, the big "25" and the following little "25" is not shown (it is rendered instead of a card-title if it is set. So the optional card-title is never rendered).

![IMG_0873](https://github.com/user-attachments/assets/5f4f21e8-d210-4b9a-a57b-4fb876b39995)

This is the correspondig code from the card js:

```css
  ha-icon {
    color: var(--paper-item-icon-color);
  }
  img {
    width: ${config.icons_size}px;
    height: ${config.icons_size}px;
  }
  .card {
    padding-top: ${config.title ? '0px' : '16px'};
```

Every variable value is rendered directly into the html. The first variable is `config.icon_size` which renders the first (big) "25". Then in the next line it is again `config.icon_size` which renders the second (little) "25". After that the variable `config.title` is evaluated. When i define a title (that again is never rendered) it shows "0px" otherwise "16px" as in the image above. So it seems to be some strange escaping issue. Unfortunately i cannot inspect the html within the companion app.

**Comment by Kanecaine** [comment]
Seems to be a bug in the ios companion app as some rendering issues are mentioned in the bug tracker, see the link above.

**Comment by knuckleheadsmiff** [comment]
I have the issue shown in the link too BUT even on a regular browser not in the companion app I can’t see the hourly status icons.  If you look at my post above you can see the icons missing even though the card mostly looks correct. Again, that image of mine above was NOT in the companion app.

**Comment by Kanecaine** [comment]
@knuckleheadsmiff Which browser are you using. I suppose this is something different. Maybe the missing icons can be brought back by clearing the browser cache - in Firefox pressing STRG + R works like wonders in some situations like this.

**Comment by knuckleheadsmiff** [comment]
> @knuckleheadsmiff Which browser are you using? I suppose this is something different. Maybe the missing icons can be brought back by clearing the browser cache - in Firefox pressing STRG + R works like wonders in some situations like this.

It is actually the same on the HA iPhone app running on the iPhone and on the safari browser on the iPad or iPhone. It’s not a cache issue.

**Comment by nvdael** [comment]
> @knuckleheadsmiff Which browser are you using? I suppose this is something different. Maybe the missing icons can be brought back by clearing the browser cache - in Firefox pressing STRG + R works like wonders in some situations like this.
> 
> edit: tried it with Safari 17.5 and i see the icons. So i really think this could be a browser cache problem, so try CMD + R.

As I mentioned in my post yesterday, I experienced it on safari and the companion app.
Both are first runs on a fresh installed iPad, so cache cannot be an issue.

https://github.com/mlamberts78/weather-chart-card/issues/222#issuecomment-2276275773

**Comment by Kanecaine** [comment]
Ok, I understand. However, I think that these are maybe 2 different problems that need to be distinguished. 

(1) In one case, css-styles (like "16px 28 100") are rendered and as a result other things like the title, all information above the graph despite icons, wind speed and direction underneath the graph are not displayed. This problem only occurs in the companion app. This is described in the original post https://github.com/mlamberts78/weather-chart-card/issues/222#issue-2454452068 ... does anyone have this outside the app in another browser?

(2) In another case, the daily weather icons are missing (which at least i cannot confirm on my devices). This problem occurs both in the app and in the Safari browser on the iPad and looks as described here https://github.com/mlamberts78/weather-chart-card/issues/222#issuecomment-2276197711 ...

@vlado05 confirmed a faulty display in the Fully Kiosk browser on an NSPanel. I assume this refers to the second case where only the icons are missing?

**Comment by knuckleheadsmiff** [comment]
#2 above is also on the iPhone (ha app and safari browser).

**Comment by jzielke84** [comment]
Possibly related to https://github.com/home-assistant/iOS/issues/2908

**Comment by Kanecaine** [comment]
Here is a workaround: if you are using card mod, paste this yaml in a new card and place this new card before the one which is buggy:

```yaml
type: custom:weather-chart-card
entity: 'bad'
card_mod:
  style: |
    ha-card {
     display: none;
    }
```

It is important to not using the UI editor, because it tries to auto-corrects the bad yaml. Place only the lines above and hit „save“. Because of card mod this faulty card is not shown, but it prevents your card from the display bug.

Credits are going to here: https://github.com/home-assistant/iOS/issues/2908#issuecomment-2282785629

**Comment by edgarveersel** [comment]
Thank you, @Kanecaine, this indeed works. After checking the original thread, I now only put in this, which also works:
```
type: custom:weather-chart-card
entity: 'bad'
```
It does however create a box. 
<img width="400" alt="Scherm­afbeelding 2024-08-16 om 13 20 32" src="https://github.com/user-attachments/assets/5245e0e4-6159-4e3b-82c1-51e46647f1bd">

which I could hide by adding a random condition that always fails in 'visibility'. Although it generates an error in Dashboard Edit mode, but it shows fine in the regular dashboard.

**Comment by mlamberts78** [comment]
PR from @piitaya was partly working, icon and text sizes where messy after update. reopened.

**Comment by mlamberts78** [comment]
Fixed with latest IOS APP update 2024.8

**Comment by greg520820** [comment]
Still doesn't render correctly on Android tablet running fully kiosk.  Get the following:

![image](https://github.com/user-attachments/assets/60518dba-3dff-4db4-ac4f-abe6d365e68d)

**Comment by knuckleheadsmiff** [comment]
It’s because HA core says that you have a legacy browser. They fixed the iPad issue in the front end update. Why they changed the legacy browser support is beyond me.

**Comment by greg520820** [comment]
> It’s because HA core says that you have a legacy browser. They fixed the iPad issue in the front end update. Why they changed the legacy browser support is beyond me.
 
According to the link and quote below there may not be any plans to fix it in  HA and instead needs to be fixed in the custom card code. 

"As a fix, The custom card code needs to use static styles and adapt the style using css variables and classes (classMap and styleMap) instead of using dynamic style with template literals. I don't think we can fix it on the HA side."

https://github.com/home-assistant/iOS/issues/2908#issuecomment-2293615805

**Comment by knuckleheadsmiff** [comment]
Yea, well they also broke a bunch of unmaintained cards like the weather radar card on browsers where it worked. I don’t under their legacy browser policy but I think it’s broken in how they close to not support (or define) legacy browsers.

**Comment by jzielke84** [comment]
> Version 2.4.9 still doesn't render correctly on an Android tablet running fully kiosk. Core version 2024.8.3 Get the following display:
> 
> ![image](https://private-user-images.githubusercontent.com/85527415/361602471-60518dba-3dff-4db4-ac4f-abe6d365e68d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MzUzNjYsIm5iZiI6MTcyNDczNTA2NiwicGF0aCI6Ii84NTUyNzQxNS8zNjE2MDI0NzEtNjA1MThkYmEtM2RmZi00ZGI0LWFjNGYtYWJlNmQzNjVlNjhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDA1MDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliYmM3YjlmMjI3ODRjY2Q1ZTEyOGJiM2RjM2NkODkxNDAyNGEyNDQ1YzQ1ZDBlMDQyYzZjYzllOWI3ZmQzMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qkB4T2jUeuckIJIj7LhobFM0k5Be6uWB3fTCljw_25o)

 Confirmed
