### ISSUE TITLE
Refresh needed when card width is changed

### ISSUE THREAD

**Issue by erkr** [mlamberts78/weather-chart-card#68]
**Describe the bug**
When I rotate my phone, the available card width changes. The card correctly adapts the number of columns (hourly) according the available width, but I need to refresh the screen (iPhone companion app) when I rotate from landscape to portrait or visa versa

**To Reproduce**
I open the hourly view in landscape:
![image](https://github.com/mlamberts78/weather-chart-card/assets/4363599/f2aa3afa-d0dd-440a-97ba-fee4ba1acd10)
Then rotate the mobile back to portrait:
![image](https://github.com/mlamberts78/weather-chart-card/assets/4363599/392f43b5-a0e3-480c-8b70-2524a6e60dcc)
After a manual refresh it is back to normal:
![image](https://github.com/mlamberts78/weather-chart-card/assets/4363599/a3f7b376-6e02-4c2d-b1d3-5812b499c926)

**Expected behavior**
I think the card needs an auto refresh when the available card width is modified

**Screenshots**
See above

**Comment by erkr** [comment]
@mlamberts78 
Thanks for looking into this issue. Is this already in a release? I just checked V2.3.1 and that version still requires a refresh after a width change.
Best Eric

**Comment by mlamberts78** [comment]
@erkr , V2.3.1 should fix the issue. Tested width change on IOS 17.3.1, Android 14 and on Windows Chrome 121.0.6167.189 browser.
On all, when changing orientation or browser width, the amount of forecasts is reduced to ensure they fit on the card.

**Comment by erkr** [comment]
@mlamberts78 
You are right, I put the card directly in the view and that it works both in the companion app and Safari on my iPhone iOS 17.3.1.
It is still not working when I embed the weather card in
`custom:tabbed-card`. Then it still needs a refresh:
![image](https://github.com/mlamberts78/weather-chart-card/assets/4363599/0dc7d116-1ae0-46bd-8844-e3639f42daae)

I'm not a Lovelace developer, but can imagine the issue is caused by that tabbed card (not forwarding the width changes to the embedded card for instance)? If so I will raise an issue there.

Thanks for fixing!
